### ISSUE TITLE
Проверка md5

### ISSUE THREAD

**Issue by skurudo** [abbat/ydcmd#1]
Добрый день.

Хотелось бы уточнить, проверяется ли файл при загрузке или после на целостность?
Имеется пачка больших файлов от 1гб и очень боязно закачать битый файл.

Судя по опциям вроде skip-md5 (отключение проверки), то опция проверки включена по умолчанию. Если возможность как-то проверить файлы или увидеть в логах контрольные суммы?

PS: Спасибо за отличный софт, мне он очень понравился.

**Comment by abbat** [comment]
> проверяется ли файл при загрузке или после на целостность?

Нет, непосредственно при/после загрузки не проверяется. Однако, при выполнении повторной операции put (над тем же набором данных) при наличии файла в облаке будет произведена проверка md5 для исключения повторной загрузки файла (если тип, размер, md5 совпадают и отключено шифрование, то загрузка будет пропущена). Опция `--skip-md5` позволяет пропустить эту проверку и проверять только тип/размер (может быть актуально для ускорения синхронизации больших наборов данных, где проверка целостности может производится реже, чем сама синхронизация).

Возможно имеет смысл добавить опцию, чтобы проверка производилась сразу после загрузки файла, но пока не совсем понятно по какому алгоритму действовать, если md5 не будет совпадать (останавливаться? пытаться загружать один и тот же файл до победного?)
