### ISSUE TITLE
Ключ командной строки для указания пути до config-файла

### ISSUE THREAD

**Issue by Baltazar500** [abbat/ydcmd#10]
В случае использования утилиты под win в среде cygwin (мне проще на баше скрипты писать), оная отказывается авторизоваться, ввиду того (как я понимаю), что пытается найти конфиг по виндовым путям, ввиду чего не помешал бы ключ для указания пути до конфига (раз уж из родной папки он не подхватывается а только из папки профиля)

**Comment by abbat** [comment]
Под cygwin конфиг должен лежать в домашней директории пользователя в окружении самого cygwin. Т.е., например, cygwin установлен в директорию `c:\cygwin`, а имя пользователя `baltazar`. Тогда путь до конфига будет `c:\cygwin\home\baltazar\.ydcmd.cfg`. Это можно проверить следующим образом:
```
$ python
Python 2.7.9 (default, May  5 2015, 12:40:14)
[GCC 4.9.2] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.expanduser("~") + "/.ydcmd.cfg"
'/home/user/.ydcmd.cfg'
```
Соответственно под cygwin должны быть установлены: `python`, `python-setuptools`, плюс необходимо установить `python-dateutil` вручную (на сколько я знаю, его нет в стандартных портах cygwin):
```
$ /usr/bin/easy_install-2.7 python-dateutil
```
