### ISSUE TITLE
make app for pCloud

### ISSUE THREAD

**Issue by mehargags** [abbat/ydcmd#12]
Hi Anton,
I’ve been using your yandex CMD app for more than an year…. I was wondering if you can create a similar app for this service called pcloud. They provide rest API
https://docs.pcloud.com/methods/file/uploadfile.html

you can get free 50GB if you attach your Hotmail/onedrive!

**Comment by abbat** [comment]
Did you try [pfs](https://github.com/pcloudcom/) or [pclsync](https://github.com/pcloudcom/pclsync)? Or it has insufficient features?

**Comment by mehargags** [comment]
No I never saw they existed... I searched for pcloud on github but did not get any results.

Will check them out for sure

Thanks alot !




Warm Regards,



Gagan


________________________________

**Comment by mehargags** [comment]
HI Anton,

I checked... they are all obsolete and old apps.


Infact I don't want to mount the whole pcloud drive, I want to simply upload a file from my server to a specific folder inside my pcloud. This enables me to upload my backup archives from different servers to separate folders inside pCloud.


Just for your info, they give 10GB free and would give 50GB free if you attach your microsoft one drive account !


Let me know if you plan to code this




Warm Regards,



Gagan


________________________________

**Comment by abbat** [comment]
Project started at https://github.com/abbat/pclcmd. It may take a long time before the first usable release.

**Comment by mehargags** [comment]
Thank you so much for listening Anton... Much appreciate

**Comment by mehargags** [comment]
Hi Anton,

thanks for starting the project.


is https://github.com/abbat/pclcmd READY to USE ?? or still being developed ?


Sorry I'm not a dev and not familiar much with GIT & Repos




THANKS a LOT



Gagan


________________________________

**Comment by abbat** [comment]
No, it is not ready. For first release I need month or more.

**Comment by mehargags** [comment]
Ok Anton
I've marked your git repo

Shall wait for your update.

Warm Regards,

Gagan
________________________________
