### ISSUE TITLE
Md5 Check for File integrtiy of uploads

### ISSUE THREAD

**Issue by mehargags** [abbat/ydcmd#2]
Thanks for this wonderful gem... I'n using it for backing up my Server Backups.
I upload tar files of 1.5Gb each daily, so I want to ensure that the the file's uploaded via the file "put" command checks the uploaded file by its Md5 checksum? is the bytecode verified & the uploaded file is checked for integrity?
We want to ensure -- the file uploaded is "byte by byte" exact copy of our local file.

in the manual of ydcmd -- it says there is an argument you can pass
--skip-md5 - skip md5 integrity checks;

which makes me presume by default it uses Md5 hash checks... please do confirm this.

Thanks alot.

**Comment by abbat** [comment]
Dup #1. Strictly speaking, you can not check integrity of uploaded file without downloading it and comparing hashes. But, you can execute "put" again on same file or directory and ydcmd skips uploading file(s) with the same (local and remote) md5.

**Comment by mehargags** [comment]
Sorry not understood fully. You mean If I issue a put again right after the upload complete... it will Match the MD5 and Not upload anything if the sum matches ??

**Comment by abbat** [comment]
Yes. Information about MD5 (which you can see in `stat` command output) used to check __local__ file modifications only and if it matches, file not upload again.

**Comment by mehargags** [comment]
Thanks alot for the Clear up....
and so if the Checksum doesn't match -- it will OverWrite ??? right ?

**Comment by abbat** [comment]
Yes. If size (first check) or md5 (second check if remote size is equal to local size) differs, it will overwrite remote file.

**Comment by mehargags** [comment]
Thanks --- ! Its clear..

just want to ask - Can we run a differential on local and YD Directories and upload the Files that exist on local and not on YD ?

**Comment by abbat** [comment]
Yes. Without `--rsync` option `put` command works as "append/replace" command. With `--rsync` it also deletes remote files what not exists on local side. Just example:

```
$ mkdir tmp
$ echo "1" > tmp/1.txt
$ echo "2" > tmp/2.txt
$ ydcmd put tmp/ disk:/tmp/
$ ydcmd ls disk:/tmp
      2  1.txt
      2  2.txt
$ echo "3" > tmp/3.txt
$ ydcmd put tmp/ disk:/tmp/
$ ydcmd ls disk:/tmp
      2  1.txt
      2  2.txt
      2  3.txt
$ rm tmp/1.txt
$ ydcmd put tmp/ disk:/tmp/
$ ydcmd ls disk:/tmp
      2  1.txt
      2  2.txt
      2  3.txt
$ ydcmd --rsync put tmp/ disk:/tmp/
$ ydcmd ls disk:/tmp
      2  2.txt
      2  3.txt
```

**Comment by mehargags** [comment]
thanks Abbat for your detailed explaination!! it works..

You just made a wonderful API script for my server backups... Keep up the good work!
