### ISSUE TITLE
optparse?

### ISSUE THREAD

**Issue by ikv** [abbat/ydcmd#20]
Есть какая-то особая причина почему аргументы коммандной строки разбираюся вручную, а не через optparse?

Могу поработать над PR если это нужно.

**Comment by abbat** [comment]
Единственная причина - это то, что модуль python-argparse является отдельным пакетом, а изначально предполагалось "скопировал скрипт и работай". Возможно сейчас это уже не актуально и можно переписать добавив необходимые зависимости в пакеты.

**Comment by ikv** [comment]
Понял.

Pull request по топику интересен будет?

**Comment by abbat** [comment]
Да, только нужно будет протестировать на популярных дистрибутивах (включая CentOS 6 и Arch - с ними чаще всего возникают тонкости, т.к. у первого python сильно старый, у второго сильно новый) и по возможности MacOS.
