### ISSUE TITLE
Скомпилированный для win релиз ?

### ISSUE THREAD

**Issue by Baltazar500** [abbat/ydcmd#26]
Понадобилась намедни программа (давно не пользовался ибо сейчас редко выгружаю), а старый релиз отвалился - пишет 400-ю ошибку "bad request". Сунулся на гитхаб за новой версией, а тут лишь исходники. Есть готовые бинарники ?

**Comment by abbat** [comment]
Можно попробовать эти: https://yadi.sk/d/zC8GyPYMggqbZ

**Comment by abbat** [comment]
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by Baltazar500** [comment]
Т.е. нужен vc++ 2017 ? Просто на момент запуска у меня уже стояли vc++ 2008, 2013 и 2015 redistributable + vc++ 2015 additional и 2015 minimum runtime.

Гугл для фикса ошибки предлагае ставить как раз 2015-й :D

**Comment by Baltazar500** [comment]
Поставил на vbox ибо особой уверенности, что там эта либа будет не было. Таки оказалась :D либа весом 80 кб ! Которая полностью стопорила работу программы. Закинул в папку с программой и всё завелось без установки vc++ Добавьте в комплект https://yadi.sk/d/qRBlpef1jNwU4g

**Comment by abbat** [comment]
Данную библиотеку нельзя добавить из за лицензионных ограничений - она должна распространяться только в составе соответствующих пакетов Microsoft.
