### ISSUE TITLE
Копирование папки без удаления содержимого облака

### ISSUE THREAD

**Issue by sawerrus** [abbat/ydcmd#29]
Есть ли возможность синхронизировать папки с облаком в одностороннем порядке, то есть добавлять новые файлы и папки и не трогать старые на облаке даже если они отсутствуют на сервере.
Хранилище облака гораздо больше чем на сервере, и хотелось бы хранить бекаппов больше чем  возможности сервера

**Comment by abbat** [comment]
Да, по умолчанию без параметра `--rsync` команда `put` загружает новые файлы, но не удаляет отсутствующие на сервере. Очистку в облаке можно производить отдельным вызовом команды `clean` указав соответствующее количество дней или количество файлов для хранения в параметрах `--keep` и `--type`. Чтобы не удалить случайно лишнего, лучше поэкспериментировать на какой-нибудь тестовой директории.

**Comment by sawerrus** [comment]
Да, без rsync все куль работает. Осталось удалять архивы скажем 15 дневной давности по дате создания, Есть ли примеры задачи ? Сильно поможете, не силен пока в этом деле

**Comment by abbat** [comment]
```
$ ydcmd clean --type=file --keep=15d --dry --debug /path/to/backup/
```
Выведет список файлов к удалению. Без параметра `--dry` удалит их.

**Comment by sawerrus** [comment]
Огромное спасибо.
