### ISSUE TITLE
"PUT" fails on Big 7.5GB file

### ISSUE THREAD

**Issue by mehargags** [abbat/ydcmd#3]
Dear Abbat,

Today I tried to setup backup script on another OLD server. the Weekly Backup File has a size of 7.6 GB each, and I need to sync 3 such files.

I tried uploading directly from web interface and it uploads correctly, so YD is accepting the file I know. Only have problem with YDCMD API call.

Can you please suggest what can be wrong ?
Also is there a way I can show progress of uploaded file ? upload speed ?

I tried the following command but it **times out** I guess on bigger files.

**ydcmd --rsync put /home/backup disk:/Rn2G-FOP/**

`Transfer: /home/backup/admin.2015-02-20.tar -> disk:/Rn2G-FOP/backup/admin.2015-02-20.tar
Traceback (most recent call last):
  File "/usr/local/bin/ydcmd", line 2348, in <module>
    yd_put_cmd(options, args)
  File "/usr/local/bin/ydcmd", line 1984, in yd_put_cmd
    yd_put_sync(options, source, target)
  File "/usr/local/bin/ydcmd", line 1491, in yd_put_sync
    yd_put_file(options, sitem, titem, flist[item] if item in flist else None)
  File "/usr/local/bin/ydcmd", line 1403, in yd_put_file
    yd_put(options, source, target)
  File "/usr/local/bin/ydcmd", line 1176, in yd_put
    yd_can_query_retry(e)
  File "/usr/local/bin/ydcmd", line 781, in yd_can_query_retry
    raise e
ssl.SSLError: The read operation timed out`

**Comment by abbat** [comment]
REST API does not allow to continue uploading from error point. You can try to increase `--retries` option to retry upload on error or split file into smaller pieces via `split`, `7zip`, `rar` or other utility (see [example](https://github.com/abbat/ydcmd/blob/master/examples/sites.simple.sh) with `7zip`).

**Comment by mehargags** [comment]
abbat-- I tried with --retries=100   this time the command just sits there forever... doens't complete, doesn't throw error.

Can you check this issue yourself with a +5GB file transfer ?? May be a problem from API side, we can ask YD to fix this.

**Comment by abbat** [comment]
Oh. `--retries=100` is not good, because on error 7GB * 100 error retries = 700GB of malicious traffic. Use 3-5-10, not more. Also you can use `--debug` option to watch progress.

I transfer large files, but my connection is very fast and stable. If your connecton is not good you have to split large files into smaller pieces (100-500MB).

**Comment by abbat** [comment]
Also you can try to set `--chunk` size to lower value (4-16KB).

**Comment by mehargags** [comment]
abbat, 
my connection cannot be an issue because it is a hosted webserver with a reputed hosting provider with 100mbit uplink.

I tied debug +Verbose mode and I think it gets stuck at the next round or something.
----

root@xsdr:/home/usr# /usr/local/bin/ydcmd --rsync put /home/backup disk:/xsdr-FOP/ --timeout=600 --retries=3 --debug --chunk                              =10
--> GET https://cloud-api.yandex.net/v1/disk/resources?path=disk%3A%2Fxsdr-FOP%2Fbackup%2F&limit=0&offset=0
--> Connected to cloud-api.yandex.net:443 (TLSv1/SSLv3 ECDHE-RSA-AES128-SHA)
--> GET https://cloud-api.yandex.net/v1/disk/resources?path=disk%3A%2Fxsdr-FOP%2Fbackup%2F&limit=100&offset=0
--> Connected to cloud-api.yandex.net:443 (TLSv1/SSLv3 ECDHE-RSA-AES128-SHA)
--> MD5: /home/backup/admin.2015-02-20.tar
--> MD5: /home/backup/admin.2015-02-13.tar
Transfer: /home/backup/admin.2015-02-06.tar -> disk:/xsdr-FOP/backup/admin.2015-02-06.tar
--> GET https://cloud-api.yandex.net/v1/disk/resources/upload?path=disk%3A%2Fxsdr-FOP%2Fbackup%2Fadmin.2015-02-06.tar&overwrite=tr                              ue
--> Connected to cloud-api.yandex.net:443 (TLSv1/SSLv3 ECDHE-RSA-AES128-SHA)
--> PUT https://uploader1o.disk.yandex.net:443/upload-target/20150304T131547.103.utd.8opqd7yegx5tv4j237nxlhtrk-k1o.1051382
--> File: /home/backup/admin.2015-02-06.tar
--> Connected to uploader1o.disk.yandex.net:443 (TLSv1/SSLv3 DHE-RSA-AES128-SHA)
^Croot@xsdr:/home/usr# /usr/local/bin/ydcmd --rsync put /home/backup disk:/xsdr-FOP/ --timeout=600 --retries=3 --debug --ver                              se --chunk=10
--> GET https://cloud-api.yandex.net/v1/disk/resources?path=disk%3A%2Fxsdr-FOP%2Fbackup%2F&limit=0&offset=0
--> Connected to cloud-api.yandex.net:443 (TLSv1/SSLv3 ECDHE-RSA-AES128-SHA)
--> GET https://cloud-api.yandex.net/v1/disk/resources?path=disk%3A%2Fxsdr-FOP%2Fbackup%2F&limit=100&offset=0
--> Connected to cloud-api.yandex.net:443 (TLSv1/SSLv3 ECDHE-RSA-AES128-SHA)
--> MD5: /home/backup/admin.2015-02-20.tar
--> MD5: /home/backup/admin.2015-02-13.tar
Transfer: /home/backup/admin.2015-02-06.tar -> disk:/xsdr-FOP/backup/admin.2015-02-06.tar
--> GET https://cloud-api.yandex.net/v1/disk/resources/upload?path=disk%3A%2Fxsdr-FOP%2Fbackup%2Fadmin.2015-02-06.tar&overwrite=true
--> Connected to cloud-api.yandex.net:443 (TLSv1/SSLv3 ECDHE-RSA-AES128-SHA)
--> PUT https://uploader9h.disk.yandex.net:443/upload-target/20150304T132844.259.utd.av6oe8464f6vzyvvvdomdnksx-k9h.1465379
--> File: /home/backup/admin.2015-02-06.tar
--> Connected to uploader9h.disk.yandex.net:443 (TLSv1/SSLv3 DHE-RSA-AES128-SHA)
Traceback (most recent call last):
  File "/usr/local/bin/ydcmd", line 2348, in <module>
    yd_put_cmd(options, args)
  File "/usr/local/bin/ydcmd", line 1984, in yd_put_cmd
    yd_put_sync(options, source, target)
  File "/usr/local/bin/ydcmd", line 1491, in yd_put_sync
    yd_put_file(options, sitem, titem, flist[item] if item in flist else None)
  File "/usr/local/bin/ydcmd", line 1403, in yd_put_file
    yd_put(options, source, target)
  File "/usr/local/bin/ydcmd", line 1176, in yd_put
    yd_can_query_retry(e)
  File "/usr/local/bin/ydcmd", line 781, in yd_can_query_retry
    raise e
ssl.SSLError: The read operation timed out
root@xsdr:/home/usr#

**Comment by abbat** [comment]
```
Traceback (most recent call last):
...
 ssl.SSLError: The read operation timed out
```

This fixed in master and will be released at Friday.

```
--> PUT https://uploader1o.disk.yandex.net:443/upload-target/20150304T131547.103.utd.8opqd7yegx5tv4j237nxlhtrk-k1o.1051382
--> File: /home/backup/admin.2015-02-06.tar
--> Connected to uploader1o.disk.yandex.net:443 (TLSv1/SSLv3 DHE-RSA-AES128-SHA)
 ^C
```
You can debug traffic via tcpdump - large files can upload long time, timeout happens...

**Comment by mehargags** [comment]
so are these related issues that I can expect to be fixed this friday ?

**Comment by abbat** [comment]
Just handling "ssl.SSLError: The read operation timed out" without retry attempt.
