### ISSUE TITLE
неверно работает опиция clean --keep=2

### ISSUE THREAD

**Issue by progreccor** [abbat/ydcmd#31]
Не знаю баг это или я плохо понял документацию.
Мне нужно оставить на диске последние  два (скажем) загруженных файла.
использую команду 
`ydcmd  clean --keep=2 disk:/backup
`
`Clean: <all> keep last 2`
Однако не происходит удаление остальных файлов.

**Comment by abbat** [comment]
А с `--type=file` тоже?

**Comment by progreccor** [comment]
`[root@imrend ~]# ydcmd  clean --keep=2 --file  disk:/backup
Clean: <all> keep last 2
[root@imrend ~]#
`

Тоже никакой реакции

**Comment by progreccor** [comment]
нет новостей по багу?

**Comment by abbat** [comment]
Пока не занимался - не хватает времени :( Можете показать вывод команды на какой-нибудь тестовой директории (или реальной, если имена файлов не секретные):

```
$ ydcmd --long ls disk:/backup/
$ ydcmd --dry --keep=2 --type=file clean disk:/backup/
```
?

**Comment by progreccor** [comment]
да, конечно, никакой секретности

`[root@imrend ~]# ydcmd --long ls disk:/backup/
2019-04-08T05:49:54+00:00  2019-04-08T05:49:54+00:00        <dir>  2019.04.08
2019-04-10T17:28:58+00:00  2019-04-10T17:28:58+00:00        <dir>  2019.04.10
[root@imrend ~]# ydcmd --dry --keep=2 --type=file clean disk:/backup/
Clean: <file> keep last 2
[root@imrend ~]#
`

**Comment by progreccor** [comment]
структура выглядит вот так 
https://i.imgur.com/RVnzWwf.png

то есть disk/backup/2019.04.04/2019.04.08_pppma.imrend.ru.tar.gz

**Comment by abbat** [comment]
Команда `clean` работает только в рамках указанной директории (т.е. не рекурсивно). Соответственно, поскольку в директории `backup` есть только 2 директории и нет файлов, то ничего не удаляется.

Предположим раз в сутки делается бэкап и кладется по пути `disk:/backup/` в директорию с именем текущей даты. Через несколько дней содержимое `disk:/backup/` будет приблизительно таким:

```
2019-04-08T05:49:54+00:00  2019-04-08T05:49:54+00:00        <dir>  2019.04.08
2019-04-09T17:28:58+00:00  2019-04-09T17:28:58+00:00        <dir>  2019.04.09
2019-04-10T05:49:54+00:00  2019-04-10T05:49:54+00:00        <dir>  2019.04.10
2019-04-11T17:28:58+00:00  2019-04-11T17:28:58+00:00        <dir>  2019.04.11
2019-04-12T17:28:58+00:00  2019-04-12T17:28:58+00:00        <dir>  2019.04.12
```

Тогда вызов команды:

```
$ ydcmd --keep=2 --type=dir clean disk:/backup/
```

удалит все директории кроме последних двух (которые за 11 и 12 число).

**Comment by progreccor** [comment]
ага. понял. моя ошибка в том, что я думал он воспринимает как единицы файлы, а он воспринимает как единицы директории.
ок, тогда понятно.
значит ошибки нет.
