### ISSUE TITLE
WEBDAV - очень низкая скорость аплоада на Яндекс Диск

### ISSUE THREAD

**Issue by nailarch** [abbat/ydcmd#35]
Платного тарифа нет. Все проверял на бесплатном.
До этого более года работало на высоких скоростях вплоть до 1 Гбит/сек.
А теперь не более 500 кбит/сек )

Проверил с разных серверов (разные дата-центры).

**Comment by nailarch** [comment]
Хотя при загрузке через браузер - скорость ниже 100 Мбит не опускается - на том же бесплатном аккаунте.
Яндекс стал ограничивать WebDAV для бесплатных аккаунтов?
Может кто проверить на платном и бесплатном аккаунтах со своего сервера?

**Comment by r0ck3r** [comment]
Платный тариф. Выгрузка очень медленная (130K/s). Но, насколько я знаю, эта программа работает не через WebDAV, а через Rest API. WebDAV у яндекса, действительно, очень медленный. Использую программу впервые, поэтому не знаю как было раньше

**Comment by nailarch** [comment]
Эх, похоже придется ставить саму программу Яндекс.диск для синхронизации.
Протестил через их программу - таких ограничений по скорости нет.

**Comment by r0ck3r** [comment]
только вот на роутеры с OpenWRT она не ставится, в отличие от этой

**Comment by abbat** [comment]
ydcmd работает через REST API, проблемы с WebDAV лучше адресовать в поддержку.

**Comment by accountnujen** [comment]
Я правильно понял: сейчас скорость ydcmd около 1мбита?

**Comment by abbat** [comment]
> Я правильно понял: сейчас скорость ydcmd около 1мбита?

Зависит от многих факторов (откуда идет загрузка, размер и расширение файла).

**Comment by abbat** [comment]
```
$ head -c 100M /dev/random > test.jpg
$ time ydcmd put test.jpg disk:/test.jpg

real	0m5,606s
user	0m0,159s
sys	0m0,102s
```

Т.е. порядка 17-18MB/s
