### ISSUE TITLE
Enable Cron Email Alert on errors only

### ISSUE THREAD

**Issue by mehargags** [abbat/ydcmd#4]
Abbat,
My Crons are running properly.

However I only want them to send me an Email Alert if there was an Error in file "PUT".
can you help me write a sample .Sh script please ??

**Comment by abbat** [comment]
Something like this:

```
#!/bin/bash

OUT=$(ydcmd put ... 2>&1)
if [ "$?" -ne "0" ]; then
    echo "${OUT}"
fi
```

Set `MAILTO` in your crontab to send emails with error output.
