### ISSUE TITLE
any news about centos 8?

### ISSUE THREAD

**Issue by progreccor** [abbat/ydcmd#42]
Do you plan to release this program for Centos 8 of AlmaLinux?

**Comment by progreccor** [comment]
пока что получаю такое:

`[root@almalinux yum.repos.d]# wget https://download.opensuse.org/repositories/home:antonbatenev:ydcmd/CentOS_8/home:antonbatenev:ydcmd.repo
--2021-11-17 06:29:26--  https://download.opensuse.org/repositories/home:antonbatenev:ydcmd/CentOS_8/home:antonbatenev:ydcmd.repo
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2001:67c:2178:8::13
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.opensuse.org/repositories/home:antonbatenev:/ydcmd/CentOS_8/home:antonbatenev:ydcmd.repo [following]
--2021-11-17 06:29:27--  https://download.opensuse.org/repositories/home:antonbatenev:/ydcmd/CentOS_8/home:antonbatenev:ydcmd.repo
Reusing existing connection to download.opensuse.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.opensuse.org/repositories/home:/antonbatenev:/ydcmd/CentOS_8/home:antonbatenev:ydcmd.repo [following]
--2021-11-17 06:29:27--  https://download.opensuse.org/repositories/home:/antonbatenev:/ydcmd/CentOS_8/home:antonbatenev:ydcmd.repo
Reusing existing connection to download.opensuse.org:443.
HTTP request sent, awaiting response... 200 OK
Length: 277
Saving to: ‘home:antonbatenev:ydcmd.repo’

home:antonbatenev:ydcmd.repo  100%[=================================================>]     277  --.-KB/s    in 0s

2021-11-17 06:29:27 (5.45 MB/s) - ‘home:antonbatenev:ydcmd.repo’ saved [277/277]

[root@almalinux yum.repos.d]# yum install ydcmd
ydcmd (CentOS_8)                                                                        8.4 kB/s | 1.6 kB     00:00
Error:
 Problem: conflicting requests
  - nothing provides python >= 2.6 needed by ydcmd-2.12-13.1.noarch
  - nothing provides python-dateutil needed by ydcmd-2.12-13.1.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
[root@almalinux yum.repos.d]#
`

**Comment by abbat** [comment]
А как точно называется пакет python3 и python3-dateutil в 8-й CentOS?

**Comment by progreccor** [comment]
> А как точно называется пакет python3 и python3-dateutil в 8-й CentOS?

вот есть на эту тему https://stackoverflow.com/questions/60603445/error-problem-conflicting-requests-nothing-provides-usr-bin-python-needed-b

**Comment by progreccor** [comment]
там изначально он вроде ставится
```[root@almalinux ~]# yum install python3
ydcmd (CentOS_8)                                                                        5.4 kB/s | 1.6 kB     00:00
Package python36-3.6.8-38.module_el8.5.0+2569+5c5719bc.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

**Comment by abbat** [comment]
Поменял имена зависимостей, сейчас получается установаить?

**Comment by progreccor** [comment]
сейчас так:
```[root@almalinux yum.repos.d]# yum install ydcmd
Last metadata expiration check: 0:01:02 ago on Mon 22 Nov 2021 11:49:18 AM MSK.
Error:
 Problem: conflicting requests
  - nothing provides python36-dateutil needed by ydcmd-2.12-14.1.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by progreccor** [comment]
```
[root@almalinux yum.repos.d]# yum install python3-dateutil
Last metadata expiration check: 0:06:15 ago on Mon 22 Nov 2021 11:49:18 AM MSK.
Package python3-dateutil-1:2.6.1-6.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

**Comment by abbat** [comment]
Поправил на python3-dateutil. Сейчас пакет должен установиться.

**Comment by progreccor** [comment]
о, получилось установить!
сейчас буду тестировать

**Comment by progreccor** [comment]
тестирование прошел, можно закрывать
