### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by mehargags** [abbat/ydcmd#5]
My Backup sets have been Syncing properly till yesterday, but last two days I'm getting this Error.

>Transfer: /backup/ad.2015-03-27.tar -> disk:/backup/ad.2015-03-27.tar
><urlopen error [Errno 104] Connection reset by peer>

The other servers are syncing properly.

what Can be the problem ?

**Comment by abbat** [comment]
This is network error - there may be many reasons. Can you provide full part of `--debug` log? What size of `ad.2015-03-27.tar`? Can you connect to upload host via telnet?

**Comment by mehargags** [comment]
Sorry -- my Yandex Disk got FULL so the connection was being "reset" by the peer. I trashed some files and now it seems working.

So now I have two questions: 
1. Does the --Debug argument show if Disk is FULL ?
2. Can we use an argument or script to first check if space is there ? like Return "Disk FULL" if less than <100mb  and Die; else go ahead ?
if we can, please help me with the script please.

Thanks Alot.

**Comment by abbat** [comment]
I add "Free" field into `ydcmd info` output. You can use it like this:

```
#!/bin/bash
FREE=$(ydcmd --long info | grep 'Free:' | awk '{ print $NF; }')
if [ "${FREE}" -lt "104857600" ]; then
	echo "No space left on device"
	exit 1
fi
```
