### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

### ISSUE THREAD

**Issue by ab-kily** [abbat/ydcmd#50]
Hello and thank you for such a good tool! 

I faced a problem trying to use your tool on fresh MAC OS X installation with python installed using homebrew:
```shell
# ./ydcmd/ydcmd.py --verbose --config=./ydcmd/ydcmd.cfg mkdir test
Unsafe HTTPS connection - ca-file not used
Create: disk:/test
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

This problem could be fixed by using `--ca-file=/usr/local/etc/ca-certificates/cert.pem` but for me it seemed strange CA file wasn't detected automatically.

Trying to find out the problem I noticed that actual location of `cert.pem` is `/usr/local/etc/ca-certificates/cert.pem`, but his path is missed in `ydcmd.py` file:
```python
     cafiles = [
         "/etc/ssl/certs/ca-certificates.crt",       # Debian, Ubuntu, Arch
         "/etc/pki/tls/certs/ca-bundle.trust.crt",   # CentOS, Fedora (EV certs)
         "/etc/ssl/ca-bundle.pem",                   # OpenSUSE
         "/usr/local/share/certs/ca-root-nss.crt",   # FreeBSD
         "/usr/local/etc/openssl/cert.pem"           # MacOS and OpenSSL via Homebrew
     ]
```

Is it possible to fix this issue by adding one more cafile path?

**Comment by ab-kily** [comment]
BTW your tool works great on MACOSX (except that issue), so you could think about fixing docs to include information about  MACOSX 😁

**Comment by abbat** [comment]
> BTW your tool works great on MACOSX (except that issue), so you could think about fixing docs to include information about MACOSX grin

I have not MacOS to test changes, but I glad to see PRs from Mac users. Thanks!
