### ISSUE TITLE
[ydcmd & Win] AttributeError: 'module' object has no attribute 'uname'

### ISSUE THREAD

**Issue by Skif-off** [abbat/ydcmd#7]
При запуске получаю ошибку
```
>ydcmd.exe help
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "ydcmd.py", line 31, in <module>
AttributeError: 'module' object has no attribute 'uname'
```
Python 2.7.9, cx_Freeze 4.3.4 (win32-py2.7), на багтрекере Python нашёл http://bugs.python.org/issue8080 Как-то можно исправить?

P.S. И батник криво как-то отрабатывает: unix2dos и bitsadmin.exe не срабатывают, но это ладно - сделал всё ручками :)

**Comment by abbat** [comment]
Установите модуль [python-dateutil](https://pypi.python.org/pypi/python-dateutil).

**Comment by abbat** [comment]
Вы можете скачать новые бинарные сборки:

* [ydcmd-1.9-win32.msi](https://yadi.sk/d/8XEG-cAifbnwt)
* [ydcmd-1.9-win32.zip](https://yadi.sk/d/m2px2uCAfbnx5)

Но под Windows утилита никак не тестируется и не поддерживается.
